// Copyright bluecxt
// SPDX-License-Identifier: Apache-2.0
package eu.kanade.tachiyomi.animeextension.fr.animesama

object AnimeSamaFilters {

    val TYPE_OPTIONS = listOf(
        "Anime" to "Anime",
        "Film" to "Film",
        "Autres" to "Autres",
    )

    val LANGUAGE_OPTIONS = listOf(
        "VF" to "VF",
        "VOSTFR" to "VOSTFR",
        "VASTFR" to "VASTFR",
    )

    val STATUT_OPTIONS = listOf(
        "En cours" to "En cours",
        "Terminé" to "Terminé",
    )

    val GENRE_OPTIONS = listOf(
        "Action" to "Action",
        "Adolescence" to "Adolescence",
        "Aliens / Extra-terrestres" to "Aliens / Extra-terrestres",
        "Amitié" to "Amitié",
        "Amour" to "Amour",
        "Apocalypse" to "Apocalypse",
        "Art" to "Art",
        "Arts martiaux" to "Arts martiaux",
        "Assassinat" to "Assassinat",
        "Autre monde" to "Autre monde",
        "Aventure" to "Aventure",
        "Combats" to "Combats",
        "Comédie" to "Comédie",
        "Crime" to "Crime",
        "Cyberpunk" to "Cyberpunk",
        "Danse" to "Danse",
        "Démons" to "Démons",
        "Détective" to "Détective",
        "Donghua" to "Donghua",
        "Drame" to "Drame",
        "Ecchi" to "Ecchi",
        "Ecole" to "Ecole",
        "Enquête" to "Enquête",
        "Famille" to "Famille",
        "Fantastique" to "Fantastique",
        "Fantasy" to "Fantasy",
        "Fantômes" to "Fantômes",
        "Futur" to "Futur",
        "Ghibli" to "Ghibli",
        "Guerre" to "Guerre",
        "Harcèlement" to "Harcèlement",
        "Harem" to "Harem",
        "Harem inversé" to "Harem inversé",
        "Histoire" to "Histoire",
        "Historique" to "Historique",
        "Horreur" to "Horreur",
        "Isekai" to "Isekai",
        "Jeunesse" to "Jeunesse",
        "Jeux" to "Jeux",
        "Jeux vidéo" to "Jeux vidéo",
        "Josei" to "Josei",
        "Journalisme" to "Journalisme",
        "Mafia" to "Mafia",
        "Magical girl" to "Magical girl",
        "Magie" to "Magie",
        "Maladie" to "Maladie",
        "Mariage" to "Mariage",
        "Mature" to "Mature",
        "Mechas" to "Mechas",
        "Médiéval" to "Médiéval",
        "Militaire" to "Militaire",
        "Monde virtuel" to "Monde virtuel",
        "Monstres" to "Monstres",
        "Musique" to "Musique",
        "Mystère" to "Mystère",
        "Nekketsu" to "Nekketsu",
        "Ninjas" to "Ninjas",
        "Nostalgie" to "Nostalgie",
        "Paranormal" to "Paranormal",
        "Philosophie" to "Philosophie",
        "Pirates" to "Pirates",
        "Police" to "Police",
        "Politique" to "Politique",
        "Post-apocalyptique" to "Post-apocalyptique",
        "Pouvoirs psychiques" to "Pouvoirs psychiques",
        "Préhistoire" to "Préhistoire",
        "Prison" to "Prison",
        "Psychologique" to "Psychologique",
        "Quotidien" to "Quotidien",
        "Religion" to "Religion",
        "Réincarnation / Transmigration" to "Réincarnation / Transmigration",
        "Romance" to "Romance",
        "Samouraïs" to "Samouraïs",
        "School Life" to "School Life",
        "Science-Fantasy" to "Science-Fantasy",
        "Science-fiction" to "Science-fiction",
        "Scientifique" to "Scientifique",
        "Seinen" to "Seinen",
        "Shôjo" to "Shôjo",
        "Shônen" to "Shônen",
        "Shônen-Ai" to "Shônen-Ai",
        "Slice of Life" to "Slice of Life",
        "Société" to "Société",
        "Sport" to "Sport",
        "Super pouvoirs" to "Super pouvoirs",
        "Super-héros" to "Super-héros",
        "Surnaturel" to "Surnaturel",
        "Survie" to "Survie",
        "Survival game" to "Survival game",
        "Technologies" to "Technologies",
        "Thriller" to "Thriller",
        "Tournois" to "Tournois",
        "Travail" to "Travail",
        "Vampires" to "Vampires",
        "Vengeance" to "Vengeance",
        "Voyage" to "Voyage",
        "Voyage temporel" to "Voyage temporel",
        "Webcomic" to "Webcomic",
        "Yakuza" to "Yakuza",
        "Yaoi" to "Yaoi",
        "Yokai" to "Yokai",
        "Yuri" to "Yuri",
    )
}
