package fr.bluecxt.core.monitoring

import android.app.Application
import keiyoushi.core.BuildConfig
import kotlinx.coroutines.DelicateCoroutinesApi
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import uy.kohesive.injekt.Injekt
import uy.kohesive.injekt.api.get
import java.util.concurrent.ConcurrentHashMap

private val WEBHOOK_URL = BuildConfig.WEBHOOK_URL

@Serializable
private data class DiscordEmbedField(
    val name: String,
    val value: String,
    val inline: Boolean = false,
)

@Serializable
private data class DiscordEmbed(
    val title: String,
    val color: Int = 15158332, // Red (0xE74C3C)
    val fields: List<DiscordEmbedField>,
)

@Serializable
private data class DiscordWebhookPayload(
    val username: String = "Anime Extensions Alert",
    val embeds: List<DiscordEmbed>,
)

object ErrorWebhook {
    private val client by lazy {
        Injekt.get<eu.kanade.tachiyomi.network.NetworkHelper>().client
    }

    private val json = Json { encodeDefaults = true }
    private val mediaType = "application/json; charset=utf-8".toMediaType()

    private val sentWebhooksCache = ConcurrentHashMap<Int, Long>()
    private val webhookMutex = Mutex()
    private const val CACHE_LIFETIME_MS = 24 * 60 * 60 * 1000L // 24 hours

    /**
     * Ultra-fast 32-bit FNV-1a non-cryptographic hash for zero-allocation payload hashing.
     */
    private fun fastHash(data: String): Int {
        var hash = -2128831035
        for (char in data) {
            hash = (hash xor char.code) * 16777619
        }
        return hash
    }

    private fun shouldSend(hashKey: Int): Boolean {
        val now = System.currentTimeMillis()
        val lastSent = sentWebhooksCache[hashKey]
        if (lastSent != null && (now - lastSent) < CACHE_LIFETIME_MS) {
            return false
        }

        if (sentWebhooksCache.size > 500) {
            sentWebhooksCache.entries.removeIf { now - it.value >= CACHE_LIFETIME_MS }
        }

        sentWebhooksCache[hashKey] = now
        return true
    }

    private fun getCallerInfo(): Triple<String, String, String> {
        val stackTrace = Thread.currentThread().stackTrace

        // 1. Prefer caller from actual extension package (e.g. eu.kanade.tachiyomi.animeextension...)
        val extCaller = stackTrace.firstOrNull { element ->
            element.className.contains("animeextension")
        }

        // 2. Fallback to bluecxt core caller excluding monitoring and utility helpers
        val caller = extCaller ?: stackTrace.firstOrNull { element ->
            val cls = element.className
            cls.contains("bluecxt") &&
                !cls.contains("ErrorWebhook") &&
                !cls.contains("ErrorInterceptor") &&
                !cls.contains("JsoupExtensions") &&
                !cls.contains("SourceAuditor")
        }

        return if (caller != null) {
            val extensionClass = caller.className.substringAfterLast(".")
            val pkgName = extCaller?.className?.substringBeforeLast(".") ?: caller.className.substringBeforeLast(".")
            val version = resolveVersion(pkgName)
            Triple(extensionClass, version, "${caller.methodName}(${caller.fileName}:${caller.lineNumber})")
        } else {
            Triple("UnknownExtension", "Unknown", "UnknownMethod")
        }
    }

    private fun resolveVersion(pkgName: String): String {
        // 1. Inspect BuildConfig.VERSION_NAME generated by Gradle for the extension
        try {
            val buildConfigCls = Class.forName("$pkgName.BuildConfig")
            val field = buildConfigCls.getField("VERSION_NAME")
            val ver = field.get(null) as? String
            if (!ver.isNullOrBlank()) return ver
        } catch (_: Exception) {}

        // 2. Query Android PackageManager for the extension or host application
        try {
            val app = Injekt.get<Application>()
            val ver = app.packageManager.getPackageInfo(pkgName, 0).versionName
                ?: app.packageManager.getPackageInfo(app.packageName, 0).versionName
            if (!ver.isNullOrBlank()) return ver
        } catch (_: Exception) {}

        return "Unknown"
    }

    fun sendWebhook(
        baseUrl: String,
        url: String,
        additionalContext: List<String>,
    ) {
        val (extensionName, extensionVersion, callerDetails) = getCallerInfo()
        val enrichedContext = additionalContext + "Caller: $callerDetails"
        sendWebhook(baseUrl, url, extensionName, extensionVersion, enrichedContext)
    }

    @OptIn(DelicateCoroutinesApi::class)
    fun sendWebhook(
        baseUrl: String,
        url: String,
        extensionName: String,
        extensionVersion: String,
        additionalContext: List<String>,
    ) = GlobalScope.launch(Dispatchers.IO) {
        if (WEBHOOK_URL.isBlank()) return@launch

        val rawKey = "$extensionName:$extensionVersion:$baseUrl:$url:${additionalContext.joinToString("|")}"
        val hashKey = fastHash(rawKey)
        val shouldProceed = webhookMutex.withLock {
            shouldSend(hashKey)
        }
        if (!shouldProceed) return@launch

        try {
            val contextFormatted = additionalContext.joinToString("\n") { "• $it" }
            val payload = DiscordWebhookPayload(
                embeds = listOf(
                    DiscordEmbed(
                        title = "🚨 Erreur Extension: $extensionName (v$extensionVersion)",
                        color = 15158332,
                        fields = listOf(
                            DiscordEmbedField(name = "🌐 Domaine", value = baseUrl, inline = true),
                            DiscordEmbedField(name = "🔗 URL", value = url.take(1024), inline = false),
                            DiscordEmbedField(name = "📝 Contexte / Erreur", value = contextFormatted.take(1024).ifBlank { "Aucun détail" }, inline = false),
                        ),
                    ),
                ),
            )

            val request = Request.Builder()
                .url(WEBHOOK_URL)
                .post(json.encodeToString(DiscordWebhookPayload.serializer(), payload).toRequestBody(mediaType))
                .build()

            client.newCall(request).execute().close()
        } catch (_: Exception) {
            // Fail silently to avoid interrupting scraper/application flow
        }
    }
}
