name: CI

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!**.md"
      - "!.github/**"
      - ".github/scripts/**"
      - ".github/workflows/build_push.yml"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    uses: ./.github/workflows/reusable_build_publish.yml
    with:
      channel: 'stable'
      gradle_task: 'assembleRelease'
      apk_path: 'src/*/*/build/outputs/apk/release/*.apk'
      repo_name: 'bluecxt french repo'
      short_name: 'bluecxt'
      author: 'bluecxt'
    secrets:
      signing_key: ${{ secrets.SIGNING_KEY }}
      alias: ${{ secrets.ALIAS }}
      key_store_password: ${{ secrets.KEY_STORE_PASSWORD }}
      key_password: ${{ secrets.KEY_PASSWORD }}
      tmdb_api: ${{ secrets.TMDB_API }}
