name: CI Alpha

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    uses: ./.github/workflows/reusable_build_publish.yml
    with:
      channel: 'alpha'
      gradle_task: 'assembleRelease'
      apk_path: 'src/*/*/build/outputs/apk/release/*.apk'
      repo_name: 'bluecxt french repo alpha'
      short_name: 'bluecxt-alpha'
      author: 'bluecxt (Alpha)'
    secrets:
      signing_key: ${{ secrets.ALPHA_SIGNING_KEY }}
      alias: ${{ secrets.ALPHA_ALIAS }}
      key_store_password: ${{ secrets.ALPHA_KEY_STORE_PASSWORD }}
      key_password: ${{ secrets.ALPHA_KEY_PASSWORD }}
      tmdb_api: ${{ secrets.TMDB_API }}
