name: PR check

on:
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!.github/**'
      - '.github/workflows/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  CI_CHUNK_SIZE: 65
  IS_PR_CHECK: true

jobs:
  prepare:
    name: Prepare job
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      matrix: ${{ steps.generate-matrices.outputs.matrix }}
      delete: ${{ steps.generate-matrices.outputs.delete }}
    steps:
      - name: Checkout PR
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set env
        id: set-env
        run: |
          LATEST_MSG=$(git log -1 --pretty=%B)
          LATEST_HASH=$(git log -1 --pretty=%H)
          echo "LATEST_COMMIT_MESSAGE<<{delimiter}
          $LATEST_MSG

          Built on commit: $LATEST_HASH
          {delimiter}" >> $GITHUB_OUTPUT

      - name: Find lib changes
        id: modified-libs
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96
        with:
          files: lib/
          files_ignore: lib/**.md
          files_separator: " "
          safe_output: false

      # This step is to alert whether a bumping version might occur.
      - name: Bump extensions that uses a modified lib
        if: steps.modified-libs.outputs.any_changed == 'true'
        env:
          COMMIT_MESSAGE: ${{ steps.set-env.outputs.LATEST_COMMIT_MESSAGE }}
          CHANGED_FILES: ${{ steps.modified-libs.outputs.all_changed_files }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          chmod +x ./.github/scripts/bump-versions.py
          python3 ./.github/scripts/bump-versions.py "$COMMIT_MESSAGE" $CHANGED_FILES
          echo "!!! This PR will bumping extensions version that uses a modified lib"

      - name: Set up Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92
        with:
          cache-read-only: true

      - id: generate-matrices
        name: Generate build matrices
        run: |
          python3 ./.github/scripts/generate-build-matrices.py origin/main ${{ secrets.SIGNING_KEY != '' && 'Release' || 'Debug' }}

  build:
    name: Build extensions (${{ matrix.chunk.number }})
    needs: prepare
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ toJson(fromJson(needs.prepare.outputs.matrix).chunk) != '[]' }}
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout PR
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92
        with:
          cache-read-only: true

      - name: Prepare signing key
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          if [ -n "$SIGNING_KEY" ]; then
            echo "$SIGNING_KEY" | base64 -d > signingkey.jks
            chmod 600 signingkey.jks
          fi

      - name: Build extensions (${{ matrix.chunk.number }})
        env:
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          MEGACLOUD_API: ${{ secrets.MEGACLOUD_API }}
          KISSKH_API: ${{ secrets.KISSKH_API }}
          KISSKH_SUB_API: ${{ secrets.KISSKH_SUB_API }}
          KAISVA: ${{ secrets.KAISVA }}
          TMDB_API: ${{ secrets.TMDB_API }}
          MODULES: ${{ join(matrix.chunk.modules, ' ') }}
        run: |
          ./gradlew $MODULES

      - name: Upload APKs (${{ matrix.chunk.number }})
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        if: github.repository == github.event.pull_request.head.repo.full_name
        with:
          name: "individual-apks-${{ matrix.chunk.number }}"
          path: "**/*.apk"
          retention-days: 1

      - name: Clean up CI files
        run: rm -f signingkey.jks
