name: Scan with Detekt

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.kt"
      - "**.kts"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**.kt"
      - "**.kts"
  schedule:
     - cron: '43 0 * * 5'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false

    - name: Set up Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
      with:
        java-version: 17
        distribution: temurin

    - name: Get Detekt download URL
      id: detekt_info
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DETEKT_RELEASE_TAG: v1.23.8
        DETEKT_EXPECTED_SHA: 046263730eb5368cb344489ac36543294e8e87bd
      run: |
        gh api graphql --field tagName="$DETEKT_RELEASE_TAG" --raw-field query='
          query getReleaseAssetDownloadUrl($tagName: String!) {
            repository(name: "detekt", owner: "detekt") {
              release(tagName: $tagName) {
                releaseAssets(first: 10) {
                  nodes {
                    name
                    downloadUrl
                  }
                }
                tagCommit {
                  oid
                }
              }
            }
          }
        ' 1> gh_response.json

        DETEKT_RELEASE_SHA=$(jq --raw-output '.data.repository.release.tagCommit.oid' gh_response.json)
        if [ "$DETEKT_RELEASE_SHA" != "$DETEKT_EXPECTED_SHA" ]; then
          echo "Release tag doesn't match expected commit SHA"
          exit 1
        fi

        DETEKT_DOWNLOAD_URL=$(jq --raw-output '.data.repository.release.releaseAssets.nodes[] | select(.name | contains("detekt-cli") and endswith(".zip")) | .downloadUrl' gh_response.json)
        echo "download_url=$DETEKT_DOWNLOAD_URL" >> $GITHUB_OUTPUT

    - name: Setup Detekt
      run: |
        dest=$( mktemp -d )
        curl --request GET \
          --url ${{ steps.detekt_info.outputs.download_url }} \
          --silent \
          --location \
          --output detekt.zip
        unzip detekt.zip -d "$dest"
        # Find the executable in the unzipped folder
        DETEKT_BIN=$(find "$dest" -name detekt-cli -type f | head -n 1)
        chmod a+x "$DETEKT_BIN"
        # Move it to a cleaner path
        mkdir -p bin
        cp "$DETEKT_BIN" ./bin/detekt
        echo "$(pwd)/bin" >> $GITHUB_PATH

    - name: Run Detekt
      continue-on-error: true
      run: |
        detekt --input ${{ github.workspace }} --report sarif:${{ github.workspace }}/detekt.sarif.json

    - name: Make artifact location URIs relative
      continue-on-error: true
      run: |
        echo "$(
          jq \
            --arg github_workspace ${{ github.workspace }} \
            '. | ( .runs[].results[].locations[].physicalLocation.artifactLocation.uri |= if test($github_workspace) then .[($github_workspace | length | . + 1):] else . end )' \
            ${{ github.workspace }}/detekt.sarif.json
        )" > ${{ github.workspace }}/detekt.sarif.json

    - name: Upload results to GitHub
      uses: github/codeql-action/upload-sarif@03e4368ac7daa2bd82b3e85262f3bf87ee112f57
      with:
        sarif_file: ${{ github.workspace }}/detekt.sarif.json
        checkout_path: ${{ github.workspace }}
